# Generated by Django 3.1.2 on 2020-12-04 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(default=organization.models.gen_code, editable=False, max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('name', models.CharField(editable=False, max_length=50)),
                ('title', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
