# Generated by Django 3.1.2 on 2020-10-11 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagSamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plagfile', models.FileField(upload_to='plagfiles/')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('outfile', models.FileField(blank=True, upload_to='outputcsvfiles/')),
                ('userperson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
