# Generated by Django 3.1.2 on 2020-12-04 12:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagSamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='sample name')),
                ('plagzip', models.FileField(upload_to='plagfiles/', validators=[django.core.validators.FileExtensionValidator(['zip', 'tar', 'gz', 'rar'])])),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('outfile', models.FileField(blank=True, upload_to='outputcsvfiles/')),
                ('organization', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
