# Generated by Django 3.1.2 on 2020-11-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagsample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagsamp',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='sample name'),
        ),
    ]
